import "../index";
import {
  main1,
  main10,
  main11,
  main12,
  main13,
  main14,
  main15,
  main16,
  main17,
  main18,
  main19,
  main2,
  main20,
  main21,
  main22,
  main23,
  main24,
  main25,
  main26,
  main27,
  main28,
  main3,
  main4,
  main5,
  main6,
  main7,
  main8,
  main9,
} from "../index";
const dataMain = [
  {
    img: main1,
    p1: "Валенсия Beige",
    p2: "Барные стулья",
    price: "2 300₽",
  },
  {
    img: main2,
    p1: "Толикс-2 White Gloss",
    p2: "Барные стулья",
    price: "4 690₽",
  },
  {
    img: main3,
    p1: "Динс Velvet Yellow",
    p2: "Диваны",
    price: "28 490₽",
  },
  {
    img: main4,
    p1: "Кускен Navy Blue",
    p2: "Диваны",
    price: "2 300₽",
  },
  {
    img: main5,
    p1: "Шерона Barhat Grey",
    p2: "Двухспальные кровати",
    price: "21 990₽",
  },
  {
    img: main6,
    p1: "Авиньон-1",
    p2: "Буфеты",
    price: "18 990₽",
  },
  {
    img: main7,
    p1: "Стелла Дуб Сонома",
    p2: "Комоды",
    price: "8 990₽",
  },
  {
    img: main8,
    p1: "Равенна-1 Light",
    p2: "Комоды",
    price: "14 990₽",
  },
  {
    img: main9,
    p1: "Бенфлит Grey",
    p2: "Журнальные столы",
    price: "7 290₽",
  },
  {
    img: main10,
    p1: "Тиффани Вудлайн Крем",
    p2: "Письменные столы",
    price: "10 990₽",
  },
  {
    img: main11,
    p1: "Валенсия Beige",
    p2: "Шкафы",
    price: "19 990₽",
  },
  {
    img: main12,
    p1: "Лайт-3-170-240 Белый",
    p2: "Шкафы",
    price: "27 290₽",
  },
  {
    img: main13,
    p1: "Вилли Pink",
    p2: "Детский диван",
    price: "21 990₽",
  },

  {
    img: main14,
    p1: "Сан-Паулу Velvet Brown",
    p2: "Барные стулья",
    price: "25 990₽",
  },
  {
    img: main15,
    p1: "Валенсия Beige",
    p2: "Барные стулья",
    price: "10 990₽",
  },
  {
    img: main16,
    p1: "Валенсия Beige",
    p2: "Барные стулья",
    price: "19 990₽",
  },
  {
    img: main17,
    p1: "Шерона Barhat Grey",
    p2: "Двухспальные кровати",
    price: "21 990₽",
  },
  {
    img: main18,
    p1: "Авиньон-1",
    p2: "Буфеты",
    price: "18 990₽",
  },
  {
    img: main19,
    p1: "Стелла Дуб Сонома",
    p2: "Комоды",
    price: "8 990₽",
  },
  {
    img: main20,
    p1: "Равенна-1 Light",
    p2: "Комоды",
    price: "14 990₽",
  },
  {
    img: main21,
    p1: "Бенфлит Grey",
    p2: "Журнальные столы",
    price: "7 290₽",
  },
  {
    img: main22,
    p1: "Тиффани Вудлайн Крем",
    p2: "Письменные столы",
    price: "10 990₽",
  },
  {
    img: main23,
    p1: "Валенсия Beige",
    p2: "Шкафы",
    price: "19 990₽",
  },
  {
    img: main24,
    p1: "Лайт-3-170-240 Белый",
    p2: "Шкафы",
    price: "27 290₽",
  },
  {
    img: main25,
    p1: "Вилли Pink",
    p2: "Детский диван",
    price: "21 990₽",
  },
  {
    img: main26,
    p1: "Сан-Паулу Velvet Brown",
    p2: "Барные стулья",
    price: "25 990₽",
  },
  {
    img: main27,
    p1: "Валенсия Beige",
    p2: "Барные стулья",
    price: "10 990₽",
  },
  {
    img: main28,
    p1: "Валенсия Beige",
    p2: "Барные стулья",
    price: "19 990₽",
  },
];
export default dataMain;
