export { default as logo } from "../img/LOGO.svg";
export { default as car } from "../img/car.svg";
export { default as icon1 } from "../img/icon1.svg";
export { default as icon2 } from "../img/icon2.svg";
export { default as icon3 } from "../img/icon3.svg";
export { default as type1 } from "../img/type/type1.svg";
export { default as type2 } from "../img/type/type2.svg";
export { default as type3 } from "../img/type/type3.svg";
export { default as type4 } from "../img/type/type4.svg";
export { default as type5 } from "../img/type/type5.svg";
export { default as type6 } from "../img/type/type6.svg";
export { default as menu1 } from "../img/menyu/menu1.svg";
export { default as menu2 } from "../img/menyu/menu2.svg";
export { default as menu3 } from "../img/menyu/menu3.svg";
export { default as menu4 } from "../img/menyu/menu4.svg";
export { default as menu5 } from "../img/menyu/menu5.svg";
export { default as menu6 } from "../img/menyu/menu6.svg";
export { default as menu7 } from "../img/menyu/menu7.svg";
export { default as menu8 } from "../img/menyu/menu8.svg";
export { default as menu9 } from "../img/menyu/menu9.svg";
export { default as menu10 } from "../img/menyu/menu10.svg";
export { default as menu11 } from "../img/menyu/menu11.svg";
export { default as menu12 } from "../img/menyu/menu12.svg";
export { default as menu13 } from "../img/menyu/menu13.svg";
export { default as menu14 } from "../img/menyu/menu14.svg";
export { default as slide1 } from "../img/sliderImg/slider1.svg";
export { default as slide2 } from "../img/sliderImg/slide2.jpg";
export { default as slide3 } from "../img/sliderImg/slide3.jpg";
export {default as main1} from "../img/main/main1.svg";
export {default as main2} from "../img/main/main2.svg";
export {default as main3} from "../img/main/main3.svg";
export {default as main4} from "../img/main/main4.svg";
export {default as main5} from "../img/main/main5.svg";
export {default as main6} from "../img/main/main6.svg";
export {default as main7} from "../img/main/main7.svg";
export {default as main8} from "../img/main/main8.svg";
export {default as main9} from "../img/main/main9.svg";
export {default as main10} from "../img/main/main11.svg";
export {default as main11} from "../img/main/main11.svg";
export {default as main12} from "../img/main/main12.svg";
export {default as main13} from "../img/main/main13.svg";
export {default as main14} from "../img/main/main14.svg";
export {default as main15} from "../img/main/main15.svg";
export {default as main16} from "../img/main/main16.svg";
export {default as main17} from "../img/main/main17.svg";
export {default as main18} from "../img/main/main18.svg";
export {default as main19} from "../img/main/main19.svg";
export {default as main20} from "../img/main/main20.svg";
export {default as main21} from "../img/main/main21.svg";
export {default as main22} from "../img/main/main22.svg";
export {default as main23} from "../img/main/main23.svg";
export {default as main24} from "../img/main/main24.svg";
export {default as main25} from "../img/main/main25.svg";
export {default as main26} from "../img/main/main26.svg";
export {default as main27} from "../img/main/main27.svg";
export {default as main28} from "../img/main/main28.svg";